export const SET_BLOG_CARDS = 'SET_BLOG_CARDS';
export const SET_TOTAL_COUNT_CARDS = 'SET_TOTAL_COUNT_CARDS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PAGINATED_CARDS = 'SET_PAGINATED_CARDS';
