export const SET_BLOG_DATA = 'SET_BLOG_DATA';
export const SET_ARTICLES_LIST = 'SET_ARTICLES_LIST';
export const SET_ARTICLE_INFO = 'SET_ARTICLE_INFO';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT';
